Release Notes 4.1.0
dotnet/SqlClient pull request #1488
Opened 2022-01-26 23:19 UTC by Kaur-Parminder

2022-01-27 20:27 UTC, johnnypham commented on CHANGELOG.md
> +- Added New Attestation Protocol `None` for enclave type `VBS` with optional `AttestationUrl`. This connection string property when set will allow users to forgo enclave attestation for VBS enclaves.
```suggestion
- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1425](https://github.com/dotnet/SqlClient/pull/1425)
```

2022-01-27 20:28 UTC, johnnypham commented on release-notes/4.1/4.1.0.md
> +- Added New Attestation Protocol `None` for enclave type `VBS` with optional `AttestationUrl`. This connection string property when set will allow users to forgo enclave attestation for VBS enclaves.
```suggestion
- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1425](https://github.com/dotnet/SqlClient/pull/1425)
```

2022-01-27 21:15 UTC, DavoudEshtehari reviewed
Update [README.md](https://github.com/dotnet/SqlClient/blob/main/release-notes/README.md) too.

2022-01-27 22:15 UTC, Kaur-Parminder commented
> Update [README.md](https://github.com/dotnet/SqlClient/blob/main/release-notes/README.md) too.

Done

2022-01-28 18:11 UTC, johnnypham requested changes

2022-01-28 18:11 UTC, johnnypham commented on release-notes/4.1/4.1.0.md
> +Connection string examples:
```suggestion
Connection string example:
```

2022-01-31 19:34 UTC, Kaur-Parminder commented on CHANGELOG.md
> +## [Stable release 4.1.0] - 2022-01-28
```suggestion
## [Stable release 4.1.0] - 2022-01-31
```

2022-01-31 19:52 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1419](https://github.com/dotnet/SqlClient/pull/1419) [
```suggestion
- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1419](https://github.com/dotnet/SqlClient/pull/1419) [#1425](https://github.com/dotnet/SqlClient/pull/1425) [Read more](#use-attestation-protocol-none-to-skip-enclave-attestation-for-vbs-enclaves)
```

2022-01-31 19:53 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +### Use `Attestation Protocol = None` to skip enclave attestation for `VBS` enclaves.
```suggestion
### Use Attestation Protocol None to skip enclave attestation for VBS enclaves
```

2022-01-31 20:38 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1419](https://github.com/dotnet/SqlClient/pull/1419) [
```suggestion
- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1419](https://github.com/dotnet/SqlClient/pull/1419) [#1425](https://github.com/dotnet/SqlClient/pull/1425) [Read more](#introduce-attestation-protocol-none)
```

2022-01-31 20:38 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +### Use Attestation Protocol None to skip enclave attestation for VBS enclaves
```suggestion
### Introduce Attestation Protocol None
```

2022-01-31 21:35 UTC, DavoudEshtehari commented on release-notes/4.1/4.1.0.md
> +## Microsoft.Data.SqlClient 4.1.0 released 28 January 2022
```suggestion
## Microsoft.Data.SqlClient 4.1.0 released 31 January 2022
```

2022-01-31 21:35 UTC, DavoudEshtehari commented on release-notes/4.1/4.1.md
> +| 2022/01/28 | 4.1.0 | [release notes](4.1.0.md) |
```suggestion
| 2022/01/31 | 4.1.0 | [release notes](4.1.0.md) |
```

2022-01-31 21:35 UTC, DavoudEshtehari commented on release-notes/4.1/README.md
> +| 2022/01/28 | 4.1.0 | [release notes](4.1.0.md) |
```suggestion
| 2022/01/31 | 4.1.0 | [release notes](4.1.0.md) |
```

2022-01-31 23:20 UTC, DavoudEshtehari approved these changes

2022-01-31 23:24 UTC, johnnypham approved these changes

2022-01-31 23:31 UTC, JRahnama approved these changes

2022-02-01 00:40 UTC, merged