Release notes 4.1.0 servicing
dotnet/SqlClient pull request #1493
Opened 2022-01-28 01:48 UTC by Kaur-Parminder

Release notes 4.1.0

2022-01-28 17:51 UTC, johnnypham commented on release-notes/4.1/4.1.0.md
> +//Attestation protocol NONE with URL
I would remove this second connection string, just to emphasize that None should not be used with a URL.

2022-01-28 18:11 UTC, johnnypham requested changes

2022-01-28 18:11 UTC, johnnypham commented on release-notes/4.1/4.1.0.md
> +Connection string examples:
```suggestion
Connection string example:
```

2022-01-28 18:29 UTC, DavoudEshtehari requested changes
Missing update the `CHANGELOG.md`.

2022-01-28 18:29 UTC, DavoudEshtehari commented on release-notes/4.1/4.1.0.md
> +- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1489](https://github.com/dotnet/SqlClient/pull/1489) [
The `Read more` link is broken cause of using the special character "`". I'd suggest using a simpler title.

2022-01-31 19:27 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +## Microsoft.Data.SqlClient 4.1.0 released 28 January 2022
```suggestion
## Microsoft.Data.SqlClient 4.1.0 released 31 January 2022
```

2022-01-31 19:31 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1489](https://github.com/dotnet/SqlClient/pull/1489) [
```suggestion
- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1489](https://github.com/dotnet/SqlClient/pull/1489) [Read more](##use-attestation-protocol-none-to-skip-enclave-attestation-for-vbs-enclaves)
```

2022-01-31 19:32 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +### Use `Attestation Protocol = None` to skip enclave attestation for `VBS` enclaves.
```suggestion
### Use Attestation Protocol None to skip enclave attestation for VBS enclaves
```

2022-01-31 19:50 UTC, Kaur-Parminder commented
> Missing update the `CHANGELOG.md`.

Added

2022-01-31 20:12 UTC, DavoudEshtehari commented on release-notes/4.1/4.1.0.md
> +### Use Attestation Protocol None to skip enclave attestation for VBS enclaves
NIT: Please update the #1488 accordingly.
```suggestion
### Introduce Attestation Protocol None
```

2022-01-31 20:35 UTC, Kaur-Parminder commented on release-notes/4.1/4.1.0.md
> +- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1489](https://github.com/dotnet/SqlClient/pull/1489) [
```suggestion
- Added new Attestation Protocol `None` for `VBS` enclave types. This protocol will allow users to forgo enclave attestation for VBS enclaves. [#1489](https://github.com/dotnet/SqlClient/pull/1489) [Read more](#introduce-attestation-protocol-none)
```

2022-01-31 21:36 UTC, DavoudEshtehari commented on release-notes/4.1/4.1.md
> +| 2022/01/28 | 4.1.0 | [release notes](4.1.0.md) |
```suggestion
| 2022/01/31| 4.1.0 | [release notes](4.1.0.md) |
```

2022-01-31 21:36 UTC, DavoudEshtehari commented on release-notes/4.1/README.md
> +| 2022/01/28 | 4.1.0 | [release notes](4.1.0.md) |
```suggestion
| 2022/01/31 | 4.1.0 | [release notes](4.1.0.md) |
```

2022-01-31 23:19 UTC, DavoudEshtehari approved these changes

2022-01-31 23:23 UTC, johnnypham approved these changes

2022-01-31 23:30 UTC, JRahnama approved these changes

2022-02-01 00:40 UTC, merged