Expose SqlAuthenticationParameters on SSPIContextProvider
dotnet/SqlClient pull request #2454
Opened 2024-04-08 23:56 UTC by twsouthwick

> [!IMPORTANT]
> [Stacked](https://stacking.dev/) against #2452. Opened as a draft to enable validation, but since this is on a separate fork, GitHub does not support stacked PRs natively AFAIK

This change updates the SSPI context provider to surface information to implementers via SqlAuthenticationParameters.

As part of this change,the internal storage of SPN is changed from byte[] to string values. Majority of implementations need the string value anyway so it makes things simpler for book keeping.

Part of #2253

2025-03-03 19:22 UTC, twsouthwick commented
@mdaigle next step for sspi :)

2025-03-03 19:24 UTC, twsouthwick commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/SSPIContextProvider.cs
> +            var auth = new SqlAuthenticationParameters.Builder(
note: I'm rebuilding this, but if there's an existing one that can be reused, let me know

2025-03-10 15:47 UTC, twsouthwick commented
ping @mdaigle @cheenamalhotra

2025-03-13 17:08 UTC, twsouthwick commented
The errors appear to also be on main and are an "Access denied" for something related to certificates. It doesn't appear to be caused by my change, but let me know if you believe it is.

2025-03-14 02:44 UTC, mdaigle reviewed
I think this all makes sense to me. I'll take another look tomorrow and also see why the tests are failing.

2025-03-14 02:44 UTC, mdaigle commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
> +                return true; // Successful case, exit the loop with current SPN.
comment no longer applies

2025-03-14 02:44 UTC, mdaigle commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/SSPIContextProvider.cs
> +            var auth = new SqlAuthenticationParameters.Builder(
I don't see an instance that makes sense to reuse. They're mostly build in the context of federated auth, which isn't applicable here.

2025-03-14 20:25 UTC, mdaigle reviewed
Tests _should_ be green now. We had a build agent issue that was resolved yesterday.

2025-03-14 20:25 UTC, mdaigle commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/SSPIContextProvider.cs
> +                resource: null,
I'm also not sure how to feel about authority. In federated auth, it's assumed that authority will be present, but here we don't set a value.

Let me chat with the team to see if we'd prefer to create a new type to better represent this set of credentials.

2025-03-17 17:46 UTC, twsouthwick commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/SSPIContextProvider.cs
> +                resource: null,
Sounds good. I refactored the builder so that the same pattern can be had wherever it's used if we want to use the existing `SqlAuthenticationParameters`

2025-04-02 16:51 UTC, paulmedynski requested changes

2025-04-02 16:51 UTC, paulmedynski commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NativeSSPIContextProvider.cs
> +        protected override bool GenerateSspiClientContext(ReadOnlySpan<byte> incomingBlob, IBufferWriter<byte> outgoingBlobWriter, SqlAuthenticationParameters authParams)
I wonder if an auth parameters object specific to SSPI would be a better choice here.  With SqlAuthenticationParameters we're exposing maybe more values than are necessary.  We're also tying ourselves to future changes to SqlAuthenticationParameters that may not be appropriate for SSPI.  We may also have to explicitly document which fields we set, and which ones we don't set.

2025-04-02 16:51 UTC, paulmedynski commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
I think the convention is to add `.netcore` to the filename before the `.cs` extension when the file contains code solely intended for .NET.  @benrr101 ?

2025-04-02 16:51 UTC, paulmedynski commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlAuthenticationParameters.cs
> +            internal Builder(SqlInternalConnectionTds connection, string resource, string authority)
I think we should keep these changes, even if we make an SspiAuthenticationParameters object.

2025-04-02 16:51 UTC, paulmedynski commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/SSPIContextProvider.cs
> +            return auth;
Implicit conversion operator from Builder to SqlAuthenticationParameters?!?  Now that's surprising...

2025-04-02 17:37 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
Ah, yes, I should have noticed that. Yes, netcore only files should end in .netcore.cs.

2025-04-03 22:36 UTC, David-Engel commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NativeSSPIContextProvider.cs
> +        protected override bool GenerateSspiClientContext(ReadOnlySpan<byte> incomingBlob, IBufferWriter<byte> outgoingBlobWriter, SqlAuthenticationParameters authParams)
I'm leaning this way, too... not strongly. But it would make the interface clearer.

2025-04-03 22:40 UTC, David-Engel commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
I thought the .netcore.cs and .unix.cs convention was for back when we were using csproj based inclusion/exclusion. Do we need the extra info in the file names? Aren't we trying to get away from separate files for netfx/netcore/windows/unix and just use compiler directives?

2025-05-01 01:45 UTC, twsouthwick commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
this file has gone through a few renames for this kind of thing. Happy to rename if needed, but I'll resolve this for now

2025-05-01 01:46 UTC, twsouthwick commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NativeSSPIContextProvider.cs
> +        protected override bool GenerateSspiClientContext(ReadOnlySpan<byte> incomingBlob, IBufferWriter<byte> outgoingBlobWriter, SqlAuthenticationParameters authParams)
I created a new one (`SspiAuthenticationParameters`) since there were a few comments to this effect

2025-05-12 22:43 UTC, mdaigle approved these changes

2025-05-13 10:55 UTC, paulmedynski approved these changes

2025-05-13 14:30 UTC, merged

2025-05-13 14:44 UTC, vonzshik commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSspiContextProvider.cs
> +            _negotiateAuth ??= new(new NegotiateAuthenticationClientOptions { Package = "Negotiate", TargetName = authParams.Resource });
I'm probably missing something, but from my understanding `SspiContextProvider` attempts to generate sspi context by iterating over each `serverSpns` (which is passed via `authParams.Resource`). But because `_negotiateAuth` is cached here, if it fails for the first spn, it's also going to fail for the others since it's going to be the exact same spn.

2025-05-13 21:18 UTC, mdaigle commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSspiContextProvider.cs
> +            _negotiateAuth ??= new(new NegotiateAuthenticationClientOptions { Package = "Negotiate", TargetName = authParams.Resource });
You're right. The implementation used to reset _negotiateAuth to null if authentication failed, but that's missing now. @twsouthwick can we correct it in a follow up PR?

2025-05-14 20:29 UTC, twsouthwick commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSspiContextProvider.cs
> +            _negotiateAuth ??= new(new NegotiateAuthenticationClientOptions { Package = "Negotiate", TargetName = authParams.Resource });
Here's the PR to add that back: https://github.com/dotnet/SqlClient/pull/3347