Merge SqlDelegatedTransaction
dotnet/SqlClient pull request #2861
Opened 2024-09-14 18:51 UTC by edwardneal

Contributes to #1261.

This PR merges the SqlDelegatedTransaction class. It's slightly more complex, because it introduces a behaviour change in the .NET Framework class. I think the change is correct though.

Line 262 of the .NET Framework class was formerly:
```csharp
if(Transaction?.TransactionInformation?.Status == System.Transactions.TransactionStatus.Aborted)
```
It's now on line 257:
```csharp
if (Transaction?.TransactionInformation?.Status != TransactionStatus.Aborted)
```

This changes the .NET Framework class to align with the .NET Core codebase. Historically, both conditions were identical between codebases; PR #1216 changed this to fix a bug in .NET Core, in the process swapping the condition from `!=` to `==` in .NET Framework. I'm pretty sure this was just a typo, and the merge will correct that.

2024-11-01 18:04 UTC, benrr101 requested changes
In general it looks good - let's get the merge conflicts resolved, take a look at the comments, make sure the build succeeds, and we'll be good to go!

2024-11-01 18:04 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDelegatedTransaction.cs
> +        private Guid GetGlobalTxnIdentifierFromToken() => new Guid(new ReadOnlySpan<byte>(_connection.PromotedDTCToken, _globalTransactionsTokenVersionSizeInBytes, 16));
nit: Put the body on a new line?

2024-11-01 20:54 UTC, edwardneal commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDelegatedTransaction.cs
> +            SqlClientEventSource.Log.TryTraceEvent("SqlDelegatedTransaction.Initialize | RES | CPOOL | Object Id {0}, Client Connection Id {1}, delegating transaction.", ObjectID, usersConnection?.Cl
Thanks for this, I'm not sure on the long-term approach for tracing either; the merged codebase isn't consistent. SqlDataAdapter ([line 170](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDataAdapter.cs#L170)) uses the .NET Core trace style, while DbConnectionInternal ([line 249](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs#L249)) uses the .NET Framework one. The SqlFileStream approach is best here, I think - I'll use that here and going forward.

2024-11-01 22:24 UTC, edwardneal commented
Thanks @benrr101 - branch has been brought up to date, the trace logs left as-is and the nit around GetGlobalTxnIdentifierFromToken addressed!

2024-11-01 23:06 UTC, David-Engel commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDelegatedTransaction.cs
> +            SqlClientEventSource.Log.TryTraceEvent("SqlDelegatedTransaction.Initialize | RES | CPOOL | Object Id {0}, Client Connection Id {1}, delegating transaction.", ObjectID, usersConnection?.Cl
I believe the `<` characters were leftover from the previous BID trace format and can be removed, when convenient, along with making the spacing consistent around `|`. They currently just make trace messages look ugly in netfx, IMO.

2024-11-15 20:08 UTC, David-Engel approved these changes

2024-11-15 22:07 UTC, cheenamalhotra approved these changes

2024-11-15 22:56 UTC, benrr101 approved these changes
Not sure how I missed updating this one, but we're good!

2024-11-15 23:12 UTC, merged