Fix | Addressing documentation issues along with spelling errors
dotnet/SqlClient pull request #2889
Opened 2024-09-26 17:33 UTC by JRahnama

This PR tries to address some of the spelling errors in this repository and also addresses some of documentation issues with paramref.

2024-09-26 18:01 UTC, ErikEJ commented on tools/targets/ClientInfo.targets
Was this added by mistake?

2024-09-26 22:04 UTC, mdaigle requested changes

2024-09-26 22:04 UTC, mdaigle commented on src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SSRP.cs
> +        /// <returns>string contaning list of SVR_RESP(just RESP_DATA)</returns>
```suggestion
        /// <returns>string containing list of SVR_RESP(just RESP_DATA)</returns>
```

2024-09-26 23:48 UTC, JRahnama commented on CHANGELOG.md
> +- Changed `receive()` and `ReceiveAsync()` implementation to receive null packets on failure [#350](https://github.com/dotnet/SqlClient/pull/350)
```suggestion
- Changed `Receive()` and `ReceiveAsync()` implementation to receive null packets on failure [#350](https://github.com/dotnet/SqlClient/pull/350)
```

2024-09-27 15:20 UTC, David-Engel commented on src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SslOverTdsStream.cs
> +        /// Check if stream can be sought
```suggestion
        /// Check if stream can seek
```

2024-09-27 16:09 UTC, JRahnama commented
I wanted to mention that there are some spelling errors in the function names, as well as likely more errors in the documentation that I didn’t have time to review. To identify spelling mistakes in function names, you can run `cspell src/**/*.cs` or `cspell "src/**/*.xml` to catch the rest. You can also save the results in a .txt file by using the appropriate command with below command:

`cspell --words-only --unique "**/*.xml" | sort --ignore-case >> results.txt`

2024-09-27 16:50 UTC, mdaigle approved these changes

2024-09-27 18:06 UTC, David-Engel approved these changes

2024-09-27 19:42 UTC, merged