Align Type aliases between netfx and netcore
dotnet/SqlClient pull request #2957
Opened 2024-11-02 06:21 UTC by MichelZ

This PR solely aligns type aliases between netfx and netcore versions so they can be merged easier later.

Part of #2953

2024-11-04 19:03 UTC, benrr101 approved these changes
Looks good, but going forward, I think we can combine a couple of PRs like this together. I'm starting to get fatigue from reviewing these all independently 😅

2024-11-05 19:41 UTC, MichelZ commented
> Looks good, but going forward, I think we can combine a couple of PRs like this together. I'm starting to get fatigue from reviewing these all independently 😅

Apologies, I really thought it makes it easier for review to have smaller, more targeted PR's... Guess I was wrong :)
Will combine them in the future

2024-11-05 20:40 UTC, benrr101 commented
There's definitely a balance :) I think we'll still take stuff when it's bite-sized like this, but it just might be slow with all the overhead. On the other hand, gigantic PRs are a lot more likely to just be outright rejected

2024-11-05 20:40 UTC, benrr101 commented
/azp run

2024-11-07 19:44 UTC, mdaigle approved these changes
Looks good after merge conflicts are fixed

2024-11-07 21:03 UTC, cheenamalhotra requested changes

2024-11-07 21:03 UTC, cheenamalhotra commented on src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
> +                                            s = new string(((SqlChars)value).Value)
```suggestion
                                            s = new string(((SqlChars)value).Value);
```

2024-11-11 18:23 UTC, benrr101 commented
/azp run

2024-11-11 19:42 UTC, MichelZ commented
AZP needs a smack on the head

2024-11-15 18:12 UTC, David-Engel approved these changes

2024-11-19 06:47 UTC, MichelZ commented
@cheenamalhotra Anything I can do to move this along? Thx

2024-11-25 23:14 UTC, merged