Upgrade / align packages in test projects /
dotnet/SqlClient pull request #2980
Opened 2024-11-06 10:18 UTC by MichelZ

- Upgrade packages that are used in NETCORE only to 8+
- Upgrade packages only used in test projects to latest versions
- Upgrade XUnit / MSTest SDK
- Remove unused variables

2024-11-06 10:23 UTC, MichelZ commented
> Looks like you missed some project file updates?

Looks like the issue with the build is that the packages are not available in the officially cached version of the sqlclientdrivers feed. I've built the project locally (with nuget.org as source) and it worked fine

2024-11-06 19:23 UTC, benrr101 commented
@MichelZ Ah, yeah, I recently learned this as well. We only allow contributors to add new package versions to our internal nuget feed. I was also shown how to manually add them, so give me a bit and I'll get them added so we can kick off the build in earnest.

2024-11-11 19:38 UTC, benrr101 commented
Upstream packages have been added to the feed, let's see what azp thinks

2024-11-11 19:38 UTC, benrr101 commented
/azp run

2024-11-14 22:24 UTC, benrr101 commented
All updated - let's give it another run

2024-11-14 22:24 UTC, benrr101 commented
/azp run

2024-11-15 09:59 UTC, MichelZ commented
It seems that net462 tests are not discovered anymore. Will look into that

2024-11-16 09:02 UTC, MichelZ commented
While we're at it, I guess it makes sense to upgrade the arcade packages as well, can you cache:
Microsoft.DotNet.RemoteExecutor - 10.0.0-beta.24564.1
Microsoft.DotNet.XUnitExtensions - 10.0.0-beta.24564.1

2024-11-18 19:37 UTC, MichelZ commented
I've also seen that we sometimes seem to hit [this](https://github.com/xunit/visualstudio.xunit/issues/396) XUnit bug that would get resolved as well with this PR and make tests more stable

2024-11-18 23:38 UTC, David-Engel commented
> While we're at it, I guess it makes sense to upgrade the arcade packages as well, can you cache: Microsoft.DotNet.RemoteExecutor - 10.0.0-beta.24564.1 Microsoft.DotNet.XUnitExtensions - 10.0.0-beta.24564.1

Done!

2024-11-18 23:53 UTC, cheenamalhotra requested changes

2024-11-18 23:53 UTC, cheenamalhotra commented on NuGet.config
> +    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
Please revert this change.

2024-11-18 23:53 UTC, cheenamalhotra commented on tools/props/VersionsNet8OrLater.props
>      <MicrosoftExtensionsCachingMemoryVersion>8.0.1</MicrosoftExtensionsCachingMemoryVersion>
Can you update this too for NetFx as well and finally remove this file?

2024-11-19 19:12 UTC, MichelZ commented
/azp run

2024-11-19 19:56 UTC, benrr101 commented
/azp run

2024-11-23 18:45 UTC, cheenamalhotra commented
Package updates are coming in #2946 and then this PR could adjust changes needed, if any.

2024-11-23 19:18 UTC, MichelZ commented
Absolutely, will do

2024-11-25 23:19 UTC, benrr101 approved these changes

2025-04-29 22:54 UTC, benrr101 commented
Closing in favor of #3312 that rebuilds the branch off main and will get full CI treatment

2025-04-29 22:54 UTC, closed without merging