Use script to install ARM version of .NET on ARM because of a UseDotNet bug
dotnet/SqlClient pull request #3037
Opened 2024-11-26 15:21 UTC by MichelZ

Looks like there's a bug in the UseDotNet Azure DevOps functionality and it installs x86 .NET on ARM:
https://github.com/microsoft/azure-pipelines-tasks/issues/20300

Adding an install script to resolve this and install the proper version on ARM.
Also, the steps were added twice as prebuild and build. Removed one.

Here you can find the logs showing the x86 install:
https://dev.azure.com/sqlclientdrivers/public/_build/results?buildId=102454&view=logs&j=f62ec789-9893-5f91-3293-e8a10244adaa&t=83eb4f36-b8e6-57c5-1c44-e749ef0d4796
```
Starting: Initialize job
Agent name: 'ADO-CI-PUBLIC-ARM64-1ES-EUS-POOL 4'
```

```
Version 9.0.100 was not found in cache.
Getting URL to download .NET Core sdk version: 9.0.100.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.248.1\externals\get-os-platform.ps1'"
Primary:win-x86
Detected platform (Primary): win-x86
Downloading: https://download.visualstudio.microsoft.com/download/pr/d7af32e6-aaec-4fcd-aabe-0d927fa73a6d/80bbc4143ee82e40b8b4341795e92f4e/dotnet-sdk-9.0.100-win-x86.zip
Extracting downloaded package D:\a\_work\_temp\5c2afe6a-65ec-4414-ad1a-8368aeaecbe9.
Extracting archive
```

**Note: This needs new packages added to the azure devops feed cache:**
**- microsoft.netcore.app.host.win-arm64 (I guess 8.0 & 9.0?)**

`
##[error]tools\GenAPI\Microsoft.DotNet.GenAPI\Microsoft.DotNet.GenAPI.csproj(0,0): Error NU1301: Failed to retrieve information about 'Microsoft.NETCore.App.Host.win-arm64' from remote source 'https://sqlclientdrivers.pkgs.visualstudio.com/904996cc-6198-4d39-8540-eca72bdf0b7b/_packaging/e8fc87e8-fcf4-4bb0-a818-96a9fdd52378/nuget/v3/flat2/microsoft.netcore.app.host.win-arm64/index.json'.
`

2024-11-27 10:22 UTC, ErikEJ commented
@MichelZ Maybe you can use the VS Code AzureDevops YAML validator 😄 ?

2024-11-27 10:26 UTC, MichelZ commented
> @MichelZ Maybe you can use the VS Code AzureDevops YAML validator 😄 ?
Today I learned....    Thanks!

2024-11-27 10:33 UTC, ErikEJ commented
@MichelZ I just got too painful watching 😆

2025-02-11 07:21 UTC, MichelZ commented
@David-Engel  Is this something that's interesting or shall I abandon this one?
The ARM build is still using the x86 compat layer instead of native:
https://sqlclientdrivers.visualstudio.com/public/_build/results?buildId=107325&view=logs&jobId=f62ec789-9893-5f91-3293-e8a10244adaa&j=f62ec789-9893-5f91-3293-e8a10244adaa&t=83eb4f36-b8e6-57c5-1c44-e749ef0d4796

```
Primary:win-x86
Detected platform (Primary): win-x86
Downloading: https://download.visualstudio.microsoft.com/download/pr/139daba9-b797-4dc9-a5a3-873604311459/90623d54cab92d97f66343147e318d6a/dotnet-sdk-9.0.102-win-x86.zip
```

If it's interesting, some packages need to be cached in the nuget source:
e.g.    `Microsoft.NETCore.App.Host.win-arm64`

2025-02-11 23:37 UTC, David-Engel commented
This is more up the alley of @benrr101 or @mdaigle. I'm sure it'll annoy them to see yet another pipeline problem that we should address. Squeaky wheel gets the grease. 😄

2025-02-14 20:20 UTC, mdaigle commented
/azp run

2025-02-14 20:29 UTC, benrr101 commented
Considering all the ARM64 pipeline runs are failing, I am curious if this might resolve it, since I can't repro it on an ARM64 vm.

Fingers crossed I added the required packages to the internal feed in time for the pipeline to run.

2025-02-17 11:15 UTC, MichelZ commented
As far as I can tell the problems started after the latest .NET SDK updates for 9.0.200, so this somehow feels like a .NET SDK bug

2025-02-17 11:19 UTC, MichelZ commented
While I haven't found an exact match, here's another macOS specific issue with dotnet restore:
https://github.com/dotnet/sdk/issues/46857

2025-02-19 18:28 UTC, benrr101 commented
@MichelZ well the good news is we fixed the issue with the CI pipeline (rebuilding our ARM64 VM images to get newer version of VS that is compatible with dotnet 9.0.200). So hopefully we can finally get some joy running these tests

2025-02-19 18:42 UTC, benrr101 requested changes
I like the idea, but I'd be nice to polish it up a bit

2025-02-19 18:42 UTC, benrr101 commented on eng/pipelines/common/templates/steps/ensure-dotnet-version.yml
> +  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
How about instead of doing this as a condition buried in the task definition, let's move this a level higher and use the `${{ if eq(variables.Agent.OS, 'Windows_NT') }}:` to conditionally include the tasks.

2025-02-19 18:42 UTC, benrr101 commented on eng/pipelines/common/templates/steps/ensure-dotnet-version.yml
> +- name: version
Since we're working on improving our pipelines (and I'm pushing for some degree of uniformity), can we have these with:
* 4 space indents at each level
* Extra line between parameter definitions and tasks
* Sort parameters alphabetically

2025-02-19 18:42 UTC, benrr101 commented on eng/pipelines/common/templates/steps/ensure-dotnet-version.yml
> +- name: sdk
Why not just have this as a string with values of 'sdk' and 'runtime' - that way when it's passed into the later tasks, we don't have to have if expressions

2025-02-21 06:59 UTC, MichelZ commented
Without CI running automatically I don't see a path forward for me to work on this. Feel free to take this over, else please close it

2025-02-21 07:04 UTC, apoorvdeshmukh commented
/azp run

2025-02-21 18:05 UTC, benrr101 commented
@MichelZ affirm 🫡  I'll take it over and re-release as a PR from the dotnet fork.

2025-02-21 20:53 UTC, benrr101 commented
Closing in favor of #3175

2025-02-21 20:53 UTC, closed without merging