Support special casing with Fabric endpoints
dotnet/SqlClient pull request #3084
Opened 2024-12-17 06:55 UTC by ErikEJ

Support the special  casing for Fabric endpoints

2024-12-17 17:58 UTC, edwardneal reviewed
Only one comment on the code style, but the checks themselves are correct.

I think there are a handful of [feature differences](https://learn.microsoft.com/en-us/fabric/database/sql/feature-comparison-sql-database-fabric) between Azure SQL and Fabric SQL which merit a test suite and documentation updates though. At a glance, the driver would be impacted by the lack of support for Always Encrypted and the BULK INSERT statement.

2024-12-17 17:58 UTC, edwardneal commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
> +                                                                        ".database.fabric.microsoft.com"};
Perhaps this should be a resource string?

2024-12-17 18:20 UTC, ErikEJ commented
@edwardneal There are a number of feature differences between the many engine variations this driver supports or happen to work with - is it really the responsibility of the driver to document this, or is the page you are linking to not enough?

2024-12-17 18:37 UTC, edwardneal commented
I think the page I linked to would cover most cases, I'm thinking primarily about a once-over to make sure that the SqlClient documentation doesn't contradict it and is clear enough for people to understand what functionality the feature depends upon. The example I had in mind was `SqlBulkCopy` - it might not be obvious that the lack of BULK INSERT support blocks this feature. I think that's probably the root cause of #2995.

2024-12-17 18:40 UTC, ErikEJ commented
#2995 refers to Fabric warehouse,  which is something completely different from Fabric SQL Database

2024-12-19 20:53 UTC, edwardneal commented
Sorry, slightly delayed here!

You're right, but the root cause is similar: some of SqlClient's functionality can't be supported on a particular engine variation, because that functionality relies upon a feature the engine doesn't support (in this case, SqlBulkCopy relies upon the BULK INSERT statement, which neither Fabric Warehouse nor Fabric SQL Database support.)

My broader point is that we should make sure that the SqlClient documentation for functionality which depends on BULK INSERT or Always Encrypted doesn't claim to be compatible across all engine variations, and that specifically for SqlBulkCopy we should make it clear that the feature depends upon server-side BULK INSERT support (since that's hard to discover in the documentation, and without that insight it's hard to know what won't support the feature.) If you want to keep this PR scoped specifically to the endpoint detection, I'm happy enough to check that documentation in a separate PR.

2025-02-27 19:19 UTC, ErikEJ commented
@mdaigle any thoughts on this?

2025-03-06 20:07 UTC, cheenamalhotra commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
>          internal static readonly string[] s_azureSqlServerEndpoints = { StringsHelper.GetString(Strings.AZURESQL_GenericEndpoint),
There are quite a few endpoints we could add here, e.g. https://learn.microsoft.com/en-us/fabric/security/fabric-allow-list-urls#data-warehouse and yes, they need not be localized.

2025-03-06 20:12 UTC, cheenamalhotra commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
> +                                                                        ".database.fabric.microsoft.com"};
They are included in the resource files, but not localized, so seems unnecessary to add them to resource files.

2025-03-06 20:18 UTC, ErikEJ commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
>          internal static readonly string[] s_azureSqlServerEndpoints = { StringsHelper.GetString(Strings.AZURESQL_GenericEndpoint),
I will look into that.

2025-03-06 20:21 UTC, ErikEJ commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
> +                                                                        ".database.fabric.microsoft.com"};
Ok, so no need to localize any of them??

2025-03-07 05:28 UTC, cheenamalhotra commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
> +                                                                        ".database.fabric.microsoft.com"};
Yes, please move them to constants.

2025-03-07 06:41 UTC, ErikEJ commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
>          internal static readonly string[] s_azureSqlServerEndpoints = { StringsHelper.GetString(Strings.AZURESQL_GenericEndpoint),
@cheenamalhotra Are all the 7 endpoint listed in your link similar to Synapse serverless??

2025-03-10 16:56 UTC, mdaigle requested changes
Thanks for cleaning up the resource files!
I just have two small requests.

2025-03-14 02:04 UTC, cheenamalhotra commented on src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
>          internal static readonly string[] s_azureSqlServerEndpoints = { StringsHelper.GetString(Strings.AZURESQL_GenericEndpoint),
They're Fabric DW endpoints - so yes, they're serverless and synapse (data warehouse).

2025-03-14 02:05 UTC, cheenamalhotra commented
@ErikEJ do review and update docs where the current endpoints are mentioned. Thanks!

2025-03-20 07:03 UTC, ErikEJ commented
@cheenamalhotra @mdaigle  Docs updated and PR feedback addressed

2025-03-20 07:23 UTC, ErikEJ commented
@cheenamalhotra @mdaigle CI never kicked in??

2025-03-20 07:38 UTC, ErikEJ commented
I used the new resource designer in VS for the removal, please make sure to review the Designer file changes.

2025-03-20 10:52 UTC, paulmedynski approved these changes

2025-03-20 10:52 UTC, paulmedynski commented
/azp run

2025-03-20 16:54 UTC, mdaigle approved these changes

2025-03-20 17:48 UTC, ErikEJ commented
I will revert the Designer changes..

2025-03-21 08:54 UTC, ErikEJ commented
@mdaigle Designer changes reverted

2025-03-21 10:37 UTC, paulmedynski commented
> @mdaigle Designer changes reverted

I liked the Designer changes - mostly fixing typos from what I could see.  Did this cause problems elsewhere?

Also, you seem to have rebased _and_ pushed 1 new commit to revert the Designer changes, but GitHub still has me marked as Approved.  I haven't reviewed the rebase nor the 1 new commit, so that's weird.

2025-03-21 11:53 UTC, ErikEJ commented
@paulmedynski The designer changes caused the build to fail. 

Lets try to avoid scope creep, I am happy to submit a new PR with the designer changes next. (And yes, it looked like mostly typos)

2025-03-21 12:03 UTC, merged

2025-03-21 12:26 UTC, ErikEJ commented
@paulmedynski The PR pipeline was not run 😢 - hope I did not break main 🙏

2025-03-21 12:45 UTC, paulmedynski commented
Sigh, I will monitor.  Looks good so far though.