Merge | Cleanup Pre 2005 Support in TdsParser
dotnet/SqlClient pull request #3085
Opened 2024-12-18 07:20 UTC by MichelZ

Now that #2839 is merged, the Pre 2005 Code can be removed from netfx to align netfx & netcore code for future merge of TdsParser.

It also removes asserts that were used to gate 2005-only code

The code does not aim to remove Pre 2005 Code from other classes

This is working towards #2953

2025-01-03 15:45 UTC, edwardneal commented
Looks good to me. Once this PR's merged, I've got a branch ready to submit ([diff](https://github.com/MichelZ/SqlClient/compare/pr/tdsparser-remove-sql-2000...edwardneal:SqlClient:merge/remove-sql-2000?w=1) - about half the size of this PR) which chases the references to `TdsParser.Is2005OrNewer` and `SqlLoginAck.isVersion8` and removes the now-redundant code.

2025-03-07 12:12 UTC, paulmedynski requested changes
I love seeing old code get removed!

2025-03-07 12:12 UTC, paulmedynski commented on src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
> +        private bool _is2005 = false;
I think we should remove this field entirely.

2025-03-07 20:22 UTC, benrr101 commented
Meant to close this in favor of #3206

2025-03-07 20:22 UTC, closed without merging