Tests | Remove hardcoded credentials from ManualTests
dotnet/SqlClient pull request #3090
Opened 2024-12-30 14:28 UTC by edwardneal

This PR mops up almost all of the remaining hardcoded credentials, and does three things:
* Removes references to `CertificateUtility.CreateCertificate`, which always used a hardcoded certificate.
* Forces the tests to dynamically generate keys in Azure Key Vault.
* Removes references to `CertificateUtilityWin` in `CspProviderExt`, then the class itself.

#### Removal of hardcoded credentials ####

The removal of CertificateUtility.CreateCertificate is pretty uncontroversial. However, the [`AKVTest.TestRoundTripWithAKVAndCertStoreProvider`](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/AKVTests.cs#L132-L146) test tries to round-trip encrypted column data, encrypting it with the hardcoded certificate and decrypting it with the Azure Key Vault key. I've thus treated this key as another static credential and removed it.

It's worth noting that the [`CoreCryptoTests`](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/CoreCryptoTests.cs) class loads hardcoded credentials from TCECryptoNativeBaselineRsa.txt. I've not touched this because I don't know what to do with it. It isn't testing any SqlClient-specific functionality, just .NET's ability to decrypt text which is encrypted by native code. I'm not sure whether this is necessary any more though: we already test this implicitly with the end-to-end AE tests. There's no modification required here - just a choice on whether to keep or delete the test entirely.

#### CspProviderExt tests ####

One partially-related change was to remove CertificateUtilityWin. This was only ever used by the [`CspProviderExt`](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/CspProviderExt.cs) tests, which used RSACryptoServiceProvider to generate a key in a specific CSP and encrypt/decrypt data with it. This consisted of three tests:
1. TestKeysFromCertificatesCreatedWithMultipleCryptoProviders, which looked for all CSPs with a name containing "RSA and AES", then generated a key in that CSP and tested the Always Encrypted provider with it.
2. TestRoundTripWithCSPAndCertStoreProvider, which generated a certificate and tried to round-trip between the certificate-based AE provider and the CSP-based AE provider. XUnit was already being told to skip this test.
3. TestEncryptDecryptWithCSP, which did exactly the same thing as test 1, but with a hard-coded CSP of "Microsoft Enhanced RSA and AES Cryptographic Provider".

Tests 1 and 3 are actually identical. "Microsoft Enhanced RSA and AES Cryptographic Provider" is the only CSP which fits the criteria for Test 1. I've thus eliminated test 1, and modified test 3 to run against all matching CSPs.

Of the remaining two tests, TestEncryptDecryptWithCSP would run a PowerShell script to generate a certificate, then extract the private key and use this as the CSP. It didn't need to do this, it could simply instantiate an RSACryptoServiceProvider directly and use that. I've thus eliminated the certificate generation. The round-trip test did need the certificate though, so I've just switched it to use the same certificate generation fixture as the rest of the tests. It still fails if I force it to run, but it fails with the same error as before. Once these changes were done, CertificateUtilityWin was no longer referenced and could be deleted wholesale.

The CspProviderExt/CertificateUtilityWin changes comprise around half of the changes. If it's easier to review, I can split them into a separate PR.

2025-02-20 22:38 UTC, benrr101 requested changes
Absolutely fantastic! Just a few changes I'd like to see made, but otherwise I fully support these changes!

2025-02-20 22:38 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/SQLSetupStrategyCspProvider.cs
> +            _cspKeyParameters.Add(cspParameters);
Am I right that there's only one parameter going in here? Do we need this to be a list?

2025-02-20 22:38 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestTrustedMasterKeyPaths.cs
> +                string invalidKeyPath = string.Format(@"{0}/my/{1}", StoreLocation.CurrentUser.ToString(), dummyThumbprint);
I don't see where `c` is being used int this (or the original) - can we either have the values be useful or just make it be a for loop? (or remove it if it's not useful)

2025-02-20 22:38 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
> +            if (_akvUrl != AKVUrl)
as far as I can tell this variable isn't being used to do anything other than indicate that the token has been acquired. If that's true, I'd recommend either making it a bool or checking `_authority`/`_resource` for `null` as the check. 

But I'm also wondering, can we store the access token itself? Or does that need to be re-acquired each time the call to this method is made? If we can store the access token, we could use `_accessToken` as the value to check here (plus we could get rid of `_authority` and `_resource`.

2025-02-20 22:38 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Fixtures/CspCertificateFixture.cs
> +        public X509Certificate2 CspCertificate { get; }
Properties after constructor, please :)

2025-02-20 22:38 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Fixtures/ColumnMasterKeyCertificateFixture.cs
> +        public X509Certificate2 ColumnMasterKeyCertificate { get; }
Properties after constructor, please :)

2025-02-24 07:45 UTC, edwardneal commented on src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
> +            if (_akvUrl != AKVUrl)
I agree. AKVUrl was used all over the place for a static AKV credential, this was the last referenced location. It's now gone!

I'm not sure about the impact that caching the access token could have on test coverage - only the first test to run would ever be able to exercise the case where the AKV access token can't be retrieved. I think it'd be better to explicitly add a TokenCredential derivative which throws and run some of the AKV tests based on that, then revisit any caching.

2025-02-24 07:47 UTC, edwardneal commented on src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestTrustedMasterKeyPaths.cs
> +                string invalidKeyPath = string.Format(@"{0}/my/{1}", StoreLocation.CurrentUser.ToString(), dummyThumbprint);
It's not - slightly odd code. I've replaced it with a collection initializer.

2025-02-24 07:48 UTC, edwardneal commented on src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/SQLSetupStrategyCspProvider.cs
> +            _cspKeyParameters.Add(cspParameters);
It's not used right now, but I've done this so that it's consistent with CertificateFixtureBase

2025-02-24 07:50 UTC, edwardneal commented on src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/SQLSetupStrategy.cs
> +            ColumnMasterKeyPath = string.Concat(StoreLocation.CurrentUser.ToString(), "/", StoreName.My.ToString(), "/", ColumnMasterKeyCertificate.Thumbprint);
I just renamed `keyPath` to something more understandable! I've made the column path formatting consistent across the tests now though.

2025-02-24 18:52 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
> +                    string AKVUrl = (new Uri(DataTestUtility.AKVBaseUri, $"/keys/{AKVKeyName}")).AbsoluteUri;
There's a level of redundant parenthesis here, right?

2025-02-24 18:53 UTC, benrr101 commented on src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
> +    <Compile Include="AlwaysEncrypted\TestFixtures\AEConnectionStringProviderWithCspParameters.cs" />
Nit: can this be moved one line up so the files are alphabetical?

2025-02-24 19:07 UTC, edwardneal commented
Thanks - I've just resolved both comments.

Won't the AE tests only run against a branch in this repo?

2025-02-27 00:04 UTC, benrr101 commented
/azp run

2025-02-27 00:08 UTC, benrr101 commented
@edwardneal ... uhhh good question. I don't think it will... :/
How about if the CI I just kicked off is successful, I can push your branch to dotnet/SqlClient and kick off a build from there to do a one-off verification.

I'm quickly getting tired of these rules that prevent us from running all our tests against external branches 😠

2025-02-27 07:21 UTC, edwardneal commented
Thanks @benrr101, that's fine by me

2025-03-06 18:41 UTC, benrr101 commented
Consider this my approval ... closing and rebuilding as #3204

Rereading my original plan I have no idea what I meant... So let's just follow the pattern that was working before.

2025-03-06 18:41 UTC, closed without merging